// cmd/generate_lunar_data.go
package main

import (
	"fmt"
	"log"
	"os"
	"remiaq/internal/services"
	"time"
)

const (
	OutputFile = "lunar_data.go"
	StartYear  = 2024
	EndYear    = 2025 // Đảm bảo bạn muốn 2024–2025
)

func main() {
	lc := services.NewLunarCalendar()
	start := time.Date(StartYear, 1, 1, 0, 0, 0, 0, time.UTC)
	end := time.Date(EndYear, 12, 31, 23, 59, 59, 0, time.UTC)

	// XÓA FILE CŨ TRƯỚC KHI GHI
	err := os.Remove(OutputFile)
	if err != nil && !os.IsNotExist(err) {
		log.Fatal("Remove old file failed:", err)
	}

	file, err := os.Create(OutputFile)
	if err != nil {
		log.Fatal("Create file failed:", err)
	}
	defer file.Close()

	// Header
	fmt.Fprintln(file, "// Code generated by cmd/generate_lunar_data.go - DO NOT EDIT")
	fmt.Fprintln(file, "// Contains: Solar to Lunar + Lunar to Solar")
	fmt.Fprintln(file, "package services")
	fmt.Fprintln(file)
	fmt.Fprintln(file, "import \"time\"")
	fmt.Fprintln(file)

	solarEntries := []string{}
	lunarEntries := []string{}
	count := 0

	for d := start; !d.After(end); d = d.AddDate(0, 0, 1) {
		vnTime := d.In(time.FixedZone("VN", 7*3600))
		lunar := lc.SolarToLunar(vnTime)

		solarKey := d.Format("2006-01-02")

		// Key âm lịch: có phân biệt tháng nhuận bằng -true
		lunarKey := fmt.Sprintf("%d-%02d-%02d", lunar.Year, lunar.Month, lunar.Day)
		if lunar.IsLeap {
			lunarKey += "-true"
		}

		// Solar to Lunar
		solarEntries = append(solarEntries, fmt.Sprintf("\t\"%s\": {%d, %d, %d, %v},",
			solarKey, lunar.Year, lunar.Month, lunar.Day, lunar.IsLeap))

		// Lunar to Solar
		lunarEntries = append(lunarEntries, fmt.Sprintf("\t\"%s\": \"%s\",", lunarKey, solarKey))

		count++
	}

	// Write SolarToLunarMap
	fmt.Fprintln(file, "var SolarToLunarMap = map[string]LunarDate{")
	for _, e := range solarEntries {
		fmt.Fprintln(file, e)
	}
	fmt.Fprintln(file, "}")
	fmt.Fprintln(file)

	// Write LunarToSolarMap
	fmt.Fprintln(file, "var LunarToSolarMap = map[string]string{")
	for _, e := range lunarEntries {
		fmt.Fprintln(file, e)
	}
	fmt.Fprintln(file, "}")

	log.Printf("Lunar data generated: %s (%d entries)", OutputFile, count)
}
