// cmd/generate_lunar_data.go
package main

import (
	"fmt"
	"log"
	"os"
	"remiaq/internal/services"
	"time"
)

const (
	OutputFile  = "CalendarMappingData.kt"
	StartYear   = 2025
	EndYear     = 2027
	PackageName = "com.yourapp.data"
)

func main() {
	lc := services.NewLunarCalendar()
	start := time.Date(StartYear, 1, 1, 0, 0, 0, 0, time.UTC)
	end := time.Date(EndYear, 12, 31, 23, 59, 59, 0, time.UTC)

	// XÓA FILE CŨ TRƯỚC KHI GHI
	err := os.Remove(OutputFile)
	if err != nil && !os.IsNotExist(err) {
		log.Fatal("Remove old file failed:", err)
	}

	file, err := os.Create(OutputFile)
	if err != nil {
		log.Fatal("Create file failed:", err)
	}
	defer file.Close()

	// Header
	fmt.Fprintln(file, "// File: CalendarMappingData.kt")
	fmt.Fprintln(file, "// Code generated by cmd/generate_lunar_data.go - DO NOT EDIT")
	fmt.Fprintln(file, "// Contains: Solar to Lunar mapping for 2024-2025")
	fmt.Fprintln(file)
	fmt.Fprintf(file, "package %s\n", PackageName)
	fmt.Fprintln(file)
	fmt.Fprintln(file, "/**")
	fmt.Fprintln(file, " * Calendar Mapping Data")
	fmt.Fprintln(file, " * Format: \"YYYY-MM-DD\" to [lunarYear, lunarMonth, lunarDay, isLeapMonth]")
	fmt.Fprintln(file, " * isLeapMonth: 0 = false, 1 = true")
	fmt.Fprintln(file, " */")
	fmt.Fprintln(file, "object CalendarMappingData {")
	fmt.Fprintln(file, "    val data: Map<String, List<Int>> = mapOf(")

	count := 0

	for d := start; !d.After(end); d = d.AddDate(0, 0, 1) {
		vnTime := d.In(time.FixedZone("VN", 7*3600))
		lunar := lc.SolarToLunar(vnTime)

		solarKey := d.Format("2006-01-02")

		// Convert boolean to int (0 or 1)
		isLeapInt := 0
		if lunar.IsLeap {
			isLeapInt = 1
		}

		// Format: "2024-01-01" to listOf(2023, 11, 20, 0),
		fmt.Fprintf(file, "        \"%s\" to listOf(%d, %d, %d, %d),\n",
			solarKey, lunar.Year, lunar.Month, lunar.Day, isLeapInt)

		count++
	}

	// Close map
	fmt.Fprintln(file, "    )")
	fmt.Fprintln(file, "}")

	log.Printf("✅ Kotlin file generated: %s (%d entries)", OutputFile, count)
	log.Printf("   Package: %s", PackageName)
	log.Printf("   Tạo từ %d-%02d-%02d đến %d-%02d-%02d",
		StartYear, 1, 1, EndYear, 12, 31)
}
